// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGGame.Infrastructure.Data;

#nullable disable

namespace RPGGame.Infrastructure.Migrations
{
    [DbContext(typeof(RPGGameDbContext))]
    [Migration("20240131110803_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RPGGame.Infrastructure.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Player identificator");

                    b.Property<int>("Agility")
                        .HasColumnType("int")
                        .HasComment("Player agility");

                    b.Property<int>("Damage")
                        .HasColumnType("int")
                        .HasComment("Player damage");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasComment("Player date created");

                    b.Property<int>("Health")
                        .HasColumnType("int")
                        .HasComment("Player health");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int")
                        .HasComment("Player intelligence");

                    b.Property<int>("Mana")
                        .HasColumnType("int")
                        .HasComment("Player mana");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Player name");

                    b.Property<int>("Range")
                        .HasColumnType("int")
                        .HasComment("Player range");

                    b.Property<int>("Strenght")
                        .HasColumnType("int")
                        .HasComment("Player strenght");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasComment("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
